name: MacOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Ninja
      run: brew install ninja

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.0'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        cache: 'true'

    - name: Install PostgreSQL
      run: brew install postgresql

    - name: List files (Debug)
      # Эта команда покажет в логах, какие файлы реально скачались.
      # Если CMakeLists.txt нет в списке, значит проблема в структуре репозитория.
      run: ls -la

    - name: Build Project
      run: |
        # Добавляем пути к PostgreSQL (для процессоров Apple Silicon M1/M2)
        # /opt/homebrew - стандартный путь для brew на новых маках
        export CMAKE_PREFIX_PATH="/opt/homebrew/opt/postgresql:$CMAKE_PREFIX_PATH"
        export CMAKE_INCLUDE_PATH="/opt/homebrew/include"
        export CMAKE_LIBRARY_PATH="/opt/homebrew/lib"
        
        # Запускаем CMake
        # -S .        -> Исходный код в текущей папке (Source)
        # -B build    -> Собирать в папку build (Build)
        # -GNinja     -> Использовать быстрый компилятор Ninja
        cmake -S . -B build \
          -GNinja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="$Qt6_DIR"

        # Компилируем
        cmake --build build

    - name: Deploy (Create DMG)
      if: success()
      working-directory: ./build
      run: |
        # Собираем все библиотеки в один файл .dmg
        macdeployqt StudyMoney.app -dmg -verbose=1

    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: StudyMoney-MacOS
        path: build/StudyMoney.dmg
