name: MacOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'

    - name: Install PostgreSQL Libs
      run: |
        brew install postgresql
        # Добавляем путь к библиотекам Homebrew (важно для M1/M2)
        echo "CMAKE_PREFIX_PATH=/opt/homebrew/opt/postgresql@14:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      working-directory: ./build
      
      run: |
        cmake .. \
        -DCMAKE_PREFIX_PATH="$Qt6_DIR;/opt/homebrew" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_OSX_ARCHITECTURES=arm64

    - name: Build
      working-directory: ./build
      run: make

    - name: Deploy (Create .dmg)
      working-directory: ./build
      run: |
        # Собираем все библиотеки в один файл
        macdeployqt StudyMoney.app -dmg -verbose=2
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StudyMoney-MacOS-Arm64
        path: build/StudyMoney.dmg
